#!/bin/bash
set -euo pipefail

ENV_FILE="/Users/Ezra/.hermes/.env"
BACKUP_DIR="/Users/Ezra/.hermes/backups"

usage() {
  cat <<'EOF'
Usage:
  ezra-admin-wrapper.sh restart-gateway
  ezra-admin-wrapper.sh restart-sshd
  ezra-admin-wrapper.sh backup-hermes-env
  ezra-admin-wrapper.sh set-hermes-env KEY VALUE
  ezra-admin-wrapper.sh install-bin SRC DST
  ezra-admin-wrapper.sh write-sshd-conf PATH
  ezra-admin-wrapper.sh set-remotelogin on|off
  ezra-admin-wrapper.sh set-ssh-authorized-keys MODE
                                       # MODE = append-literal | append-stdin
  ezra-admin-wrapper.sh install-launch-agent PLIST
  ezra-admin-wrapper.sh tailscale-funnel-set HOST PORT
  ezra-admin-wrapper.sh tailscale-funnel-off HOST
  ezra-admin-wrapper.sh write-resolver-file NAME NAMESERVER...
  ezra-admin-wrapper.sh load-launch-daemon PLIST
EOF
}

require_safe_key() {
  case "$1" in
    HINDSIGHT_LLM_API_KEY|GOOGLE_API_KEY|GEMINI_API_KEY|GOOGLE_GENERATIVE_AI_API_KEY)
      ;;
    *)
      echo "Refusing unsupported key: $1" >&2
      exit 2
      ;;
  esac
}

backup_env() {
  mkdir -p "$BACKUP_DIR"
  cp "$ENV_FILE" "$BACKUP_DIR/.env.$(date +%Y%m%d-%H%M%S).bak"
}

set_env_key() {
  local key="$1"
  local value="$2"
  require_safe_key "$key"
  backup_env
  python3 - "$ENV_FILE" "$key" "$value" <<'PY'
from pathlib import Path
import sys
path = Path(sys.argv[1])
key = sys.argv[2]
value = sys.argv[3]
lines = path.read_text().splitlines()
out = []
found = False
for line in lines:
    if line.startswith(key + "="):
        out.append(f"{key}={value}")
        found = True
    else:
        out.append(line)
if not found:
    out.append(f"{key}={value}")
path.write_text("\n".join(out) + "\n")
PY
}

restart_gateway() {
  local label="ai.hermes.gateway"
  local pid
  pid="$(launchctl list 2>/dev/null | awk -v lbl="$label" '$3==lbl {print $1; exit}')"
  if [ -n "$pid" ] && [ "$pid" != "-" ]; then
    # Live: respawn under launchd's watch — no double-run, no orphaned children.
    launchctl kickstart -k "gui/$(id -u)/$label" >/dev/null
    sleep 1
    local newpid
    newpid="$(launchctl list 2>/dev/null | awk -v lbl="$label" '$3==lbl {print $1; exit}')"
    if [ -n "$newpid" ] && [ "$newpid" != "$pid" ]; then
      echo "Restarted $label: PID $pid -> $newpid"
      return 0
    fi
    echo "$label still on PID $pid; kickstart did not rotate" >&2
    return 1
  fi
  # Not loaded (e.g. user-session-only launchd lost it). Bootstrap from the installed plist.
  local plist="$HOME/Library/LaunchAgents/$label.plist"
  if [ -f "$plist" ]; then
    launchctl bootstrap "gui/$(id -u)" "$plist"
    echo "Bootstrapped $label from $plist"
    return 0
  fi
  echo "$label not loaded and no plist at $plist" >&2
  return 1
}

install_bin() {
  # install_bin SRC DST  (0755 root, idempotent)
  local src="$1" dst="$2"
  [ -f "$src" ] || { echo "missing source: $src" >&2; exit 2; }
  /usr/bin/install -m 755 "$src" "$dst"
}

write_sshd_conf() {
  # write_sshd_conf PATH  — strict key-only sshd config snippet (mode 644)
  local path="$1"
  cat > "$path" <<'SSHD'
# Generated by ezra-admin-wrapper.sh — strict key-only config
PermitRootLogin no
PasswordAuthentication no
ChallengeResponseAuthentication no
PubkeyAuthentication yes
UsePAM yes
PrintMotd no
AcceptEnv LANG LC_*
Subsystem sftp /usr/libexec/sftp-server
SSHD
  chmod 644 "$path"
}

set_remotelogin() {
  /usr/sbin/systemsetup -setremotelogin "$1" >/dev/null
}

set_ssh_authorized_keys() {
  # MODE = append-literal | append-stdin
  local mode="$1"
  case "$mode" in
    append-literal|append-stdin) : ;;
    *) echo "bad mode: $mode" >&2; exit 2 ;;
  esac
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  touch ~/.ssh/authorized_keys
  chmod 600 ~/.ssh/authorized_keys
  local key
  key="$(cat)"
  [ -n "$key" ] || { echo "empty key on stdin" >&2; exit 2; }
  case "$key" in
    ssh-ed25519\ *|ssh-rsa\ *|ecdsa-sha2-*\ *) ;;
    *) echo "refusing key with non-allowlisted type" >&2; exit 2 ;;
  esac
  if /usr/bin/grep -qxF "$key" ~/.ssh/authorized_keys; then
    echo "OK: key already present, no change"
  else
    printf '%s\n' "$key" >> ~/.ssh/authorized_keys
    echo "OK: key appended"
  fi
}

restart_sshd() {
  # Full bring-up: clear Disabled flag, set Remote Login on, bootstrap, kickstart.
  /bin/launchctl enable system/com.openssh.sshd 2>/dev/null || true
  /usr/sbin/systemsetup -setremotelogin on >/dev/null 2>&1 || true
  /bin/launchctl bootstrap system /System/Library/LaunchDaemons/ssh.plist 2>/dev/null || true
  if /bin/launchctl kickstart -k system/com.openssh.sshd 2>&1; then
    echo "OK: kickstarted sshd"
  else
    echo "WARN: kickstart failed; check 'sudo launchctl print system/com.openssh.sshd'"
    return 1
  fi
  # Print status
  /bin/launchctl print system/com.openssh.sshd 2>/dev/null | head -3
  /usr/sbin/systemsetup -getremotelogin 2>/dev/null
}

install_launch_agent() {
  # install_launch_agent PLIST  (copies into ~/Library/LaunchAgents as $USER, then bootstraps in user domain)
  local plist="$1"
  [ -f "$plist" ] || { echo "missing plist: $plist" >&2; exit 2; }
  local label
  label="$(/usr/libexec/PlistBuddy -c 'Print :Label' "$plist")"
  local dst="$HOME/Library/LaunchAgents/${label}.plist"
  # Copy as the invoking user so the file ownership matches the bootstrap domain
  /bin/cp "$plist" "$dst"
  /bin/chmod 644 "$dst"
  /usr/sbin/chown "$(id -un)":staff "$dst"
  /bin/launchctl bootout "gui/$(id -u)/${label}" 2>/dev/null || true
  /bin/launchctl bootstrap "gui/$(id -u)" "$dst"
  /bin/launchctl enable  "gui/$(id -u)/${label}"
  /bin/launchctl kickstart "gui/$(id -u)/${label}"
  echo "OK: bootstrapped $label in gui/$(id -u)"
}

tailscale_funnel_set() {
  /Applications/Tailscale.app/Contents/MacOS/tailscale funnel --bg --https="$1" "http://127.0.0.1:$2"
}

tailscale_funnel_off() {
  /Applications/Tailscale.app/Contents/MacOS/tailscale funnel --https="$1" off
}

write_resolver_file() {
  # write_resolver_file NAME NAMESERVERS...  (e.g. write_resolver_file tail7aeffd.ts.net 100.100.100.100)
  local name="$1"; shift
  [ -n "$name" ] && [ "$#" -ge 1 ] || { echo "usage: write-resolver-file NAME NAMESERVER..." >&2; exit 2; }
  mkdir -p /etc/resolver
  local tmp
  tmp="$(/usr/bin/mktemp)"
  : > "$tmp"
  for ns in "$@"; do
    printf 'nameserver %s\n' "$ns" >> "$tmp"
  done
  /usr/bin/install -m 644 "$tmp" "/etc/resolver/${name}"
  rm -f "$tmp"
}

load_launch_daemon() {
  # load_launch_daemon PLIST  (system-level)
  local plist="$1"
  [ -f "$plist" ] || { echo "missing plist: $plist" >&2; exit 2; }
  /bin/launchctl bootstrap system "$plist" 2>/dev/null || true
  /bin/launchctl enable  system/"$(/usr/libexec/PlistBuddy -c 'Print :Label' "$plist")" 2>/dev/null || true
  /bin/launchctl kickstart -k system/"$(/usr/libexec/PlistBuddy -c 'Print :Label' "$plist")"
}

cmd="${1:-}"
case "$cmd" in
  restart-gateway)
    restart_gateway
    ;;
  restart-sshd)
    restart_sshd
    ;;
  backup-hermes-env)
    backup_env
    ;;
  set-hermes-env)
    [ "$#" -eq 3 ] || { usage; exit 2; }
    set_env_key "$2" "$3"
    ;;
  install-bin)
    [ "$#" -eq 3 ] || { usage; exit 2; }
    install_bin "$2" "$3"
    ;;
  write-sshd-conf)
    [ "$#" -eq 2 ] || { usage; exit 2; }
    write_sshd_conf "$2"
    ;;
  set-remotelogin)
    [ "$#" -eq 2 ] || { usage; exit 2; }
    set_remotelogin "$2"
    ;;
  set-ssh-authorized-keys)
    [ "$#" -eq 2 ] || { usage; exit 2; }
    set_ssh_authorized_keys "$2"
    ;;
  install-launch-agent)
    [ "$#" -eq 2 ] || { usage; exit 2; }
    install_launch_agent "$2"
    ;;
  tailscale-funnel-set)
    [ "$#" -eq 3 ] || { usage; exit 2; }
    tailscale_funnel_set "$2" "$3"
    ;;
  tailscale-funnel-off)
    [ "$#" -eq 2 ] || { usage; exit 2; }
    tailscale_funnel_off "$2"
    ;;
  write-resolver-file)
    [ "$#" -ge 3 ] || { usage; exit 2; }
    write_resolver_file "$2" "${@:3}"
    ;;
  load-launch-daemon)
    [ "$#" -eq 2 ] || { usage; exit 2; }
    load_launch_daemon "$2"
    ;;
  *)
    usage
    exit 2
    ;;
esac
